### ISSUE TITLE
Greater Wall circles miss dots

### ISSUE THREAD

**Issue by alicebob** [robx/puzzle-draw#32]
These circles are not really pretty:

https://github.com/robx/puzzle-draw/blob/master/tests/examples/greaterwall.png

**Comment by robx** [comment]
and they used to be: https://maybepuzzles.wordpress.com/2016/07/06/puzzle-110-greater-wall/

**Comment by alicebob** [comment]
I rest my case!

**Comment by robx** [comment]
Seems the fix has made it to a release by now.
